HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/Components/PagerViewComponent.cs
using HeThongQuanLyCongTacKhaoThi.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/ContestController.cs
using HeThongQuanLyCongTacKhaoThi.ApiIntegration;
using HeThongQuanLyCongTacKhaoThi.Utilities.Constants;
using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests;
using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.TeacherContests;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers
{
    [Authorize(Policy = Policy.Manager)]
    public class ContestController : Controller
    {
        private readonly IContestApiClient _contestApiClient;
        private readonly ISubjectApiClient _subjectApiClient;
        private readonly IScoreTypeApiClient _scoreTypeApiClient;
        private readonly IAccountApiClient _accountApiClient;
        private readonly ITeacherContestApiClient _teacherContestApiClient;

        public ContestController(IContestApiClient contestApiClient,
                                ISubjectApiClient subjectApiClient,
                                IScoreTypeApiClient scoreTypeApiClient,
                                IAccountApiClient accountApiClient,
                                ITeacherContestApiClient teacherContestApiClient)
        {
            _contestApiClient = contestApiClient;
            _subjectApiClient = subjectApiClient;
            _scoreTypeApiClient = scoreTypeApiClient;
            _accountApiClient = accountApiClient;
            _teacherContestApiClient = teacherContestApiClient;
        }

        public async Task<IActionResult> Index(string keyword = " ", int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetContestPagingRequest
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _contestApiClient.GetContestPaging(request);

            ViewBag.SuccessMsg = TempData["SuccessMsg"];
            return View(data.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var request = new ContestCURequest();
            // Get subjects
            var getSubjects = await _subjectApiClient.GetAll();
            var subjects = getSubjects.ResultObj;
            request.Subjects = subjects.ToList();

            // Get score types
            var getScoreTypes = await _scoreTypeApiClient.GetAllBySubjectID(subjects[0].ID);
            var scoreTypes = getScoreTypes.ResultObj;
            request.ScoreTypes = scoreTypes.ToList();

            // Get all teachers
            var getTeachers = await _accountApiClient.GetAllTeachers();
            var teachers = getTeachers.ResultObj;
            request.Teachers = teachers.ToList();

            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ContestCURequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var getContestID = await _contestApiClient.Create(request);
            if (getContestID.IsSuccessed)
            {
                await _teacherContestApiClient.Create(new TeacherContestCURequest()
                {
                    TeacherID = request.Teacher1ID,
                    ContestID = getContestID.ResultObj
                });

                if (!request.Teacher2ID.Equals(Guid.Empty))
                {
                    await _teacherContestApiClient.Create(new TeacherContestCURequest()
                    {
                        TeacherID = request.Teacher2ID,
                        ContestID = getContestID.ResultObj
                    });
                }

                TempData["SuccessMsg"] = "Tạo kỳ kiểm tra thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", getContestID.Message); 
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _contestApiClient.GetByID(id);
            if (result.IsSuccessed)
            {
                var contest = result.ResultObj;
                var updateRequest = new ContestCURequest()
                {
                    ID = contest.ID,
                    Name = contest.Name,
                    SubjectID = contest.SubjectID,
                    ScoreTypeID = contest.ScoreTypeID,
                    StartTime = contest.StartTime,
                    Duration = contest.Duration,
                    Description = contest.Description,
                    Teacher1ID = contest.Teacher1ID,
                    Teacher2ID = contest.Teacher2ID
                };

                // Get subjects
                var getSubjects = await _subjectApiClient.GetAll();
                var subjects = getSubjects.ResultObj;
                updateRequest.Subjects = subjects.ToList();

                // Get score types
                var getScoreTypes = await _scoreTypeApiClient.GetAllBySubjectID(updateRequest.SubjectID);
                var scoreTypes = getScoreTypes.ResultObj;
                updateRequest.ScoreTypes = scoreTypes.ToList();

                // Get all teachers
                var getTeachers = await _accountApiClient.GetAllTeachers();
                var teachers = getTeachers.ResultObj;
                updateRequest.Teachers = teachers.ToList();

                return View(updateRequest);
            }

            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ContestCURequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = await _contestApiClient.Update(request.ID, request);

            if (!result.IsSuccessed)
            {
                ModelState.AddModelError("", result.Message);
                return View(request);
            }


            await _teacherContestApiClient.Delete(request.ID);

            await _teacherContestApiClient.Create(new TeacherContestCURequest()
            {
                TeacherID = request.Teacher1ID,
                ContestID = request.ID
            });

            if (!request.Teacher2ID.Equals(Guid.Empty))
            {
                await _teacherContestApiClient.Create(new TeacherContestCURequest()
                {
                    TeacherID = request.Teacher2ID,
                    ContestID = request.ID
                });
            }

            TempData["SuccessMsg"] = "Cập nhật kỳ kiểm tra thành công";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _contestApiClient.GetByID(id);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            return View(result.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _contestApiClient.GetByID(id);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            return View(result.ResultObj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ContestViewModel request)
        {
            var result = await _contestApiClient.Delete(request.ID);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }

            TempData["SuccessMsg"] = "Xoá kỳ kiểm tra thành công";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetSubjectIDByContestID(int contestID)
        {
            var getSubjectID = await _contestApiClient.GetSubjectIDByContestID(contestID);

            return Json(new
            {
                success = true,
                SubjectID = getSubjectID.ResultObj
            });
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/ExamController.cs
using HeThongQuanLyCongTacKhaoThi.ApiIntegration;
using HeThongQuanLyCongTacKhaoThi.Utilities.Constants;
using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Exams;
using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.QuestionGroups;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers
{
    [Authorize(Policy = Policy.Manager)]
    public class ExamController : Controller
    {
        private readonly IExamApiClient _examApiClient;
        private readonly ISubjectApiClient _subjectApiClient;
        private readonly IContestApiClient _contestApiClient;

        public ExamController(IExamApiClient examApiClient, ISubjectApiClient subjectApiClient, IContestApiClient contestApiClient)
        {
            _examApiClient = examApiClient;
            _subjectApiClient = subjectApiClient;
            _contestApiClient = contestApiClient;
        }

        public async Task<IActionResult> Index(string keyword = " ", int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetExamPagingRequest
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _examApiClient.GetExamPaging(request);

            ViewBag.SuccessMsg = TempData["SuccessMsg"];
            return View(data.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var examCreateRequest = new ExamCreateRequest()
            {
                QuestionGroupViewModels = new List<QuestionGroupViewModel>()
            };

            // Get all contests
            var getContests = await _contestApiClient.GetAll();
            if (!getContests.IsSuccessed)
            {
                BadRequest("Không thể lấy danh sách kỳ kiểm tra");
            }
            examCreateRequest.Contests = getContests.ResultObj.ToList();

            examCreateRequest.SubjectID = getContests.ResultObj[0].SubjectID;

            return View(examCreateRequest);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExamCreateRequest request, List<int> QuestionGroups)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            if(QuestionGroups.Count == 0)
            {
                return BadRequest("Bạn cần chọn nhóm câu hỏi");
            }

            request.QuestionGroups = QuestionGroups.ToList();

            var result = await _examApiClient.Create(request);
            if (result.IsSuccessed)
            {
                TempData["CreateUpdateSuccessMsg"] = "Tạo đề thi thành công";
                return RedirectToAction("AddMaxQuestionMark", new { examID = result.ResultObj });
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _examApiClient.GetByID(id);
            if (result.IsSuccessed)
            {
                var exam = result.ResultObj;
                var updateResquest = new ExamUpdateRequest()
                {
                    ID = exam.ID,
                    Name = exam.Name,
                    ReRandom = false,
                    ContestID = exam.ContestID,
                    SubjectID = exam.SubjectID,
                    MultipleChoiceQuestionCount = exam.MultipleChoiceQuestionCount,
                    EssayQuestionCount = exam.EssayQuestionCount,
                    QuestionGroups = exam.QuestionGroups.ToList()
                };

                // Get all contests
                var getContests = await _contestApiClient.GetAll();
                if (!getContests.IsSuccessed)
                {
                    BadRequest("Không thể lấy danh sách kỳ kiểm tra");
                }
                updateResquest.Contests = getContests.ResultObj.ToList();

                return View(updateResquest);
            }

            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ExamUpdateRequest request, List<int> QuestionGroups)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (request.ReRandom && QuestionGroups.Count == 0)
            {
                return BadRequest("Bạn cần chọn nhóm câu hỏi");
            }

            request.QuestionGroups = QuestionGroups.ToList();
            var result = await _examApiClient.Update(request.ID, request);

            if (!result.IsSuccessed)
            {
                ModelState.AddModelError("", result.Message);
                return View(request);
            }

            if (request.ReRandom)
            {
                TempData["CreateUpdateSuccessMsg"] = "Cập nhật đề thi thành công";
                return RedirectToAction("AddMaxQuestionMark", new { examID = result.ResultObj });
            }

            TempData["SuccessMsg"] = "Cập nhật đề thi thành công";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _examApiClient.GetByID(id);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            return View(result.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _examApiClient.GetByID(id);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            return View(result.ResultObj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ExamViewModel request)
        {
            var result = await _examApiClient.Delete(request.ID);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }

            TempData["SuccessMsg"] = "Xoá đề thi thành công";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddMaxQuestionMark(int examID)
        {
            var result = await _examApiClient.GetByID(examID);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }

            TempData["examID"] = examID;
            return View(result.ResultObj);
        }

        [HttpPost]
        public async Task<IActionResult> AddMaxQuestionMark(List<ExamDetailCURequest> examDetails)
        {
            int examID = (int)TempData["examID"];
            var result = await _examApiClient.AddMaxQuestionMark(examID, examDetails);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            TempData["SuccessMsg"] = TempData["CreateUpdateSuccessMsg"];
            return RedirectToAction("Index");
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/QuestionGroupController.cs
using HeThongQuanLyCongTacKhaoThi.ApiIntegration;
using HeThongQuanLyCongTacKhaoThi.Utilities.Constants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers
{
    [Authorize(Policy = Policy.Manager)]
    public class QuestionGroupController : Controller
    {
        private readonly IQuestionGroupApiClient _questionGroupApiClient;

        public QuestionGroupController(IQuestionGroupApiClient questionGroupApiClient)
        {
            _questionGroupApiClient = questionGroupApiClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllQuestionGroup(int id)
        {
            var getQuestionGroups = await _questionGroupApiClient.GetAll();
            var questionGroups = getQuestionGroups.ResultObj;

            ViewData["QuestionGroups"] = new SelectList(questionGroups, "ID", "Name");
            return PartialView("_QuestionGroup", id);
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Exam/AddMaxQuestionMark.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Exams.ExamViewModel

@{
    ViewData["Title"] = "Thiết lập điểm cho câu hỏi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Thiết lập điểm cho câu hỏi</h1>

<div>
    <h4>Chi tiết các câu hỏi</h4>
    <hr />
    <form asp-action="AddMaxQuestionMark">
        <dl class="row">
            @for (int i = 0; i < Model.ExamDetails.Count; i++)
            {
                <dt class="col-12">
                    <hr>
                    <h3 class="text-bold h4 text-gray-700">Câu @(i+1)</h3>
                    <hr>
                </dt>
                var question = Model.ExamDetails[i].Question;
                @await Html.PartialAsync("_QuestionDetail", question);
                <dt class="col-sm-2">
                    Điểm câu hỏi
                </dt>
                <input type="hidden" name="examDetails[@i].QuestionID" value="@question.ID"/>
                <dd class="col-sm-10 form-group">
                    @if (!question.IsMultipleChoice)
                    {
                        <input type="number" class="form-control" name="examDetails[@i].MaxQuestionMark" min="0" max="10" value="1" step="0.25" />
                    }
                    else
                    {
                        <input type="hidden" name="examDetails[@i].MaxQuestionMark" value="0" />
                    }
                </dd>
            }
        </dl>
        <div class="form-group">
            <input type="submit" value="Thiết lập điểm" class="btn btn-primary" />
        </div>
    </form>
</div>

@section Scripts{
    <script src="/assets/vendor/ckeditor5/build/ckeditor.js"></script>

    <script>
        $(document).ready(function () {

            var addEditor = function (className) {
                window.editors = {};

                document.querySelectorAll(className).forEach((node, index) => {
                    ClassicEditor
                        .create(node, {})
                        .then(newEditor => {
                            window.editors[index] = newEditor;
                            newEditor.isReadOnly = true;
                        })
                        .catch(error => {
                            console.error('Oops, something went wrong!');
                            console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                            console.warn('Build id: 5eukpjx8rsb5-h2d357uhcalr');
                            console.error(error);
                        });
                });

            }

            addEditor('.content');
            addEditor('.editor');
        });
    </script>

}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Exam/Create.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Exams.ExamCreateRequest

@{
    ViewData["Title"] = "Tạo đề thi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tạo đề thi</h1>

<h4>Mẫu biểu tạo đề thi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Kỳ kiểm tra</label>
                <select asp-for="ContestID" class="form-control" asp-items="@(new SelectList(Model.Contests, "ID", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SubjectID" class="control-label"></label>
                <input asp-for="SubjectID" class="form-control" readonly />
                <span asp-validation-for="SubjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MultipleChoiceQuestionCount" class="control-label"></label>
                <input asp-for="MultipleChoiceQuestionCount" class="form-control" />
                <span asp-validation-for="MultipleChoiceQuestionCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EssayQuestionCount" class="control-label"></label>
                <input asp-for="EssayQuestionCount" class="form-control" />
                <span asp-validation-for="EssayQuestionCount" class="text-danger"></span>
            </div>
            <div class="form-group" id="question-groups">
            </div>
            <button type="button" id="add-question-group" class="btn btn-primary mb-3">
                <i class="fa fa-plus"></i> Thêm nhóm câu hỏi
            </button>
            <div class="form-group">
                <input type="submit" value="Tạo đề thi" class="btn btn-primary" /> |
                <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách đề thi</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {

    <script>

        $(document).ready(function () {

            // Get Subject ID follow Contest ID
            $("#ContestID").on('change', function () {
                var contestID = $(this).val();
                var url = '@Url.Action("GetSubjectIDByContestID", "Contest")?contestID=' + contestID;
                $.get(url, function (data) {
                    $("#SubjectID").val(data.subjectID);
                });
            });

            // Init & get Question Groups
            var questionGroupID = 0;
            $("#add-question-group").on('click', function () {
                var url = '@Url.Action("GetAllQuestionGroup", "QuestionGroup")/' + questionGroupID++;
                $.get(url, function (data) {
                    $("#question-groups").append(data);
                });
            });

            $("body").on('click', '#remover-question-group', function () {
                $(this).parent().parent().remove();

                // Fix element's index of questiongroups to submit
                var questionGroups = $('select[name^="QuestionGroups"]');
                $.each(questionGroups, function (index, val){
                    $(this).prop('name', 'QuestionGroups[' + index + ']');
                });

                // Fix id when add new element
                questionGroupID = questionGroups.length;
            });

        });
    </script>
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Exam/Delete.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Exams.ExamViewModel

@{
    ViewData["Title"] = "Xoá đề thi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xoá đề thi</h1>
<h3>Bạn có chắc chắn muốn xoá đề thi này?</h3>

<div>
    <h4>Thông tin đề thi sẽ xoá</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubjectID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubjectID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MultipleChoiceQuestionCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MultipleChoiceQuestionCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EssayQuestionCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EssayQuestionCount)
        </dd>
    </dl>
    <h4>Chi tiết các câu hỏi trong đề thi</h4>
    <dl class="row">
        @for (int i = 0; i < Model.ExamDetails.Count; i++)
        {
            var question = Model.ExamDetails[i].Question;
            <dt class="col-12">
                <hr>
                <h3 class="text-bold h4 text-gray-700">Câu @(i+1)</h3>
                <hr>
            </dt>

            @if (!question.IsMultipleChoice)
            {
                <dt class="col-sm-2">
                    Điểm câu hỏi
                </dt>
                <dd class="col-sm-10">
                    @(Model.ExamDetails[i].MaxQuestionMark)đ
                </dd>
            }

            @await Html.PartialAsync("_QuestionDetail", question);

        }
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Xoá" class="btn btn-danger" /> |
        <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách đề thi</a>
    </form>
</div>


@section Scripts{

    @* Enable MathJax to support render MathML on Chrome and Edge *@
    <script>window.MathJax = { MathML: { extensions: ["mml3.js", "content-mathml.js"] } };</script>
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=MML_HTMLorMML"></script>
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Exam/Edit.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Exams.ExamUpdateRequest

@{
    ViewData["Title"] = "Sửa thông tin đề thi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sửa thông tin đề thi</h1>

<h4>Mẫu biểu sửa thông tin đề thi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Kỳ kiểm tra</label>
                <select asp-for="ContestID" class="form-control" asp-items="@(new SelectList(Model.Contests, "ID", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SubjectID" class="control-label"></label>
                <input asp-for="SubjectID" class="form-control" readonly/>
                <span asp-validation-for="SubjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MultipleChoiceQuestionCount" class="control-label"></label>
                <input asp-for="MultipleChoiceQuestionCount" class="form-control" readonly />
                <span asp-validation-for="MultipleChoiceQuestionCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EssayQuestionCount" class="control-label"></label>
                <input asp-for="EssayQuestionCount" class="form-control" readonly />
                <span asp-validation-for="EssayQuestionCount" class="text-danger"></span>
            </div>
            <div class="form-group" id="question-groups">
            </div>
            <button type="button" id="add-question-group" class="btn btn-primary mb-3">
                <i class="fa fa-plus"></i> Thêm nhóm câu hỏi
            </button>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ReRandom" /> @Html.DisplayNameFor(model => model.ReRandom)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" /> |
                <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách đề thi</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {

    <script>
        $(document).ready(function () {

            // Get Subject ID follow Contest ID
            $("#ContestID").on('change', function () {
                var contestID = $(this).val();
                var url = '@Url.Action("GetSubjectIDByContestID", "Contest")?contestID=' + contestID;
                $.get(url, function (data) {
                    $("#SubjectID").val(data.subjectID);
                });
            });

            $("#ReRandom").change(function () {
                $("#MultipleChoiceQuestionCount").prop("readonly", !$("#MultipleChoiceQuestionCount").prop("readonly"));
                $("#EssayQuestionCount").prop("readonly", !$("#EssayQuestionCount").prop("readonly"));
                $('.form-inline').children().prop('disabled', false);
                $('#add-question-group').prop('disabled', false);
                $(this).parent().parent().hide();   // Hide rerandom checkbox
            });

            // Init question groups was choosen
            var url = '';
            @{
                for(int i=0; i<Model.QuestionGroups.Count; i++)
                {
                    <text>
                        url = '@Url.Action("GetAllQuestionGroup", "QuestionGroup")/' + @i;
                        $.get(url, function (data) {
                            $("#question-groups").append(data);
                            $('[name="QuestionGroups[@i]"]').val("@Model.QuestionGroups[i]");
                            $('.form-inline').children().prop('disabled', true);
                        });
                    </text>
                }
            }
            $('#add-question-group').prop('disabled', true);

            // Add question group
            var questionGroupID = @Model.QuestionGroups.Count;
            $("#add-question-group").on('click', function () {
                var url = '@Url.Action("GetAllQuestionGroup", "QuestionGroup")/' + questionGroupID++;
                $.get(url, function (data) {
                    $("#question-groups").append(data);
                });
            });

            $("body").on('click', '#remover-question-group', function () {
                $(this).parent().parent().remove();

                // Fix element's index of questiongroups to submit
                var questionGroups = $('select[name^="QuestionGroups"]');
                $.each(questionGroups, function (index, val){
                    $(this).prop('name', 'QuestionGroups[' + index + ']');
                });

                // Fix id when add new element
                questionGroupID = questionGroups.length;
            });

        });
    </script>
}