HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/Components/PagerViewComponent.cs
using HeThongQuanLyCongTacKhaoThi.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/ContestController.cs
using HeThongQuanLyCongTacKhaoThi.ApiIntegration;
using HeThongQuanLyCongTacKhaoThi.Utilities.Constants;
using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests;
using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.TeacherContests;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers
{
    [Authorize(Policy = Policy.Manager)]
    public class ContestController : Controller
    {
        private readonly IContestApiClient _contestApiClient;
        private readonly ISubjectApiClient _subjectApiClient;
        private readonly IScoreTypeApiClient _scoreTypeApiClient;
        private readonly IAccountApiClient _accountApiClient;
        private readonly ITeacherContestApiClient _teacherContestApiClient;

        public ContestController(IContestApiClient contestApiClient,
                                ISubjectApiClient subjectApiClient,
                                IScoreTypeApiClient scoreTypeApiClient,
                                IAccountApiClient accountApiClient,
                                ITeacherContestApiClient teacherContestApiClient)
        {
            _contestApiClient = contestApiClient;
            _subjectApiClient = subjectApiClient;
            _scoreTypeApiClient = scoreTypeApiClient;
            _accountApiClient = accountApiClient;
            _teacherContestApiClient = teacherContestApiClient;
        }

        public async Task<IActionResult> Index(string keyword = " ", int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetContestPagingRequest
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _contestApiClient.GetContestPaging(request);

            ViewBag.SuccessMsg = TempData["SuccessMsg"];
            return View(data.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var request = new ContestCURequest();
            // Get subjects
            var getSubjects = await _subjectApiClient.GetAll();
            var subjects = getSubjects.ResultObj;
            request.Subjects = subjects.ToList();

            // Get score types
            var getScoreTypes = await _scoreTypeApiClient.GetAllBySubjectID(subjects[0].ID);
            var scoreTypes = getScoreTypes.ResultObj;
            request.ScoreTypes = scoreTypes.ToList();

            // Get all teachers
            var getTeachers = await _accountApiClient.GetAllTeachers();
            var teachers = getTeachers.ResultObj;
            request.Teachers = teachers.ToList();

            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ContestCURequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var getContestID = await _contestApiClient.Create(request);
            if (getContestID.IsSuccessed)
            {
                await _teacherContestApiClient.Create(new TeacherContestCURequest()
                {
                    TeacherID = request.Teacher1ID,
                    ContestID = getContestID.ResultObj
                });

                if (!request.Teacher2ID.Equals(Guid.Empty))
                {
                    await _teacherContestApiClient.Create(new TeacherContestCURequest()
                    {
                        TeacherID = request.Teacher2ID,
                        ContestID = getContestID.ResultObj
                    });
                }

                TempData["SuccessMsg"] = "Tạo kỳ kiểm tra thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", getContestID.Message); 
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _contestApiClient.GetByID(id);
            if (result.IsSuccessed)
            {
                var contest = result.ResultObj;
                var updateRequest = new ContestCURequest()
                {
                    ID = contest.ID,
                    Name = contest.Name,
                    SubjectID = contest.SubjectID,
                    ScoreTypeID = contest.ScoreTypeID,
                    StartTime = contest.StartTime,
                    Duration = contest.Duration,
                    Description = contest.Description,
                    Teacher1ID = contest.Teacher1ID,
                    Teacher2ID = contest.Teacher2ID
                };

                // Get subjects
                var getSubjects = await _subjectApiClient.GetAll();
                var subjects = getSubjects.ResultObj;
                updateRequest.Subjects = subjects.ToList();

                // Get score types
                var getScoreTypes = await _scoreTypeApiClient.GetAllBySubjectID(updateRequest.SubjectID);
                var scoreTypes = getScoreTypes.ResultObj;
                updateRequest.ScoreTypes = scoreTypes.ToList();

                // Get all teachers
                var getTeachers = await _accountApiClient.GetAllTeachers();
                var teachers = getTeachers.ResultObj;
                updateRequest.Teachers = teachers.ToList();

                return View(updateRequest);
            }

            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ContestCURequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = await _contestApiClient.Update(request.ID, request);

            if (!result.IsSuccessed)
            {
                ModelState.AddModelError("", result.Message);
                return View(request);
            }


            await _teacherContestApiClient.Delete(request.ID);

            await _teacherContestApiClient.Create(new TeacherContestCURequest()
            {
                TeacherID = request.Teacher1ID,
                ContestID = request.ID
            });

            if (!request.Teacher2ID.Equals(Guid.Empty))
            {
                await _teacherContestApiClient.Create(new TeacherContestCURequest()
                {
                    TeacherID = request.Teacher2ID,
                    ContestID = request.ID
                });
            }

            TempData["SuccessMsg"] = "Cập nhật kỳ kiểm tra thành công";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _contestApiClient.GetByID(id);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            return View(result.ResultObj);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _contestApiClient.GetByID(id);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }
            return View(result.ResultObj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ContestViewModel request)
        {
            var result = await _contestApiClient.Delete(request.ID);
            if (!result.IsSuccessed)
            {
                return BadRequest(result.Message);
            }

            TempData["SuccessMsg"] = "Xoá kỳ kiểm tra thành công";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetSubjectIDByContestID(int contestID)
        {
            var getSubjectID = await _contestApiClient.GetSubjectIDByContestID(contestID);

            return Json(new
            {
                success = true,
                SubjectID = getSubjectID.ResultObj
            });
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Controllers/ScoreTypeController.cs
using HeThongQuanLyCongTacKhaoThi.ApiIntegration;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HeThongQuanLyCongTacKhaoThi.AdminApp.Controllers
{
    public class ScoreTypeController : Controller
    {
        private readonly IScoreTypeApiClient _scoreTypeApiClient;

        public ScoreTypeController(IScoreTypeApiClient scoreTypeApiClient)
        {
            _scoreTypeApiClient = scoreTypeApiClient;
        }

        public async Task<IActionResult> GetAllBySubjectID(string subjectID)
        {
            var scoreTypes = await _scoreTypeApiClient.GetAllBySubjectID(subjectID);
            return PartialView("_ScoreType", scoreTypes.ResultObj);
        }
    }
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Contest/Create.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests.ContestCURequest

@{
    ViewData["Title"] = "Tạo kỳ kiểm tra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tạo kỳ kiểm tra</h1>

<h4>Mẫu biểu tạo kỳ kiểm tra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Môn học</label>
                <select asp-for="SubjectID" class="form-control" asp-items="@(new SelectList(Model.Subjects, "ID", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Loại điểm</label>
                <select asp-for="ScoreTypeID" class="form-control" asp-items="@(new SelectList(Model.ScoreTypes, "ID", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" min="15" value="15" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giáo viên 1</label>
                <select asp-for="Teacher1ID" class="form-control" asp-items="@(new SelectList(Model.Teachers, "Id", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Giáo viên 2</label>
                <select asp-for="Teacher2ID" class="form-control" asp-items="@(new SelectList(Model.Teachers, "Id", "Name"))">
                    <option value="@Guid.Empty">Không có giáo viên 2</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo kỳ kiểm tra" class="btn btn-primary" /> |
                <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách kỳ kiểm tra</a>
            </div>
        </form>
    </div>
</div>

@section Scripts { 
    <script>
        $(document).ready(function () {
            $('#SubjectID').on('change', function () {
                var url = '@Url.Action("GetAllBySubjectID", "ScoreType")?subjectID=' + $(this).val();
                $.get(url, function (data) {
                    var parentDiv = $("#ScoreTypeID").parent();
                    $("#ScoreTypeID").remove();
                    parentDiv.append(data);
                });
            });


            // Set current datetime and block previous date
            currentDateTime = new Date();
            let hoursDiff = currentDateTime.getHours() - currentDateTime.getTimezoneOffset() / 60;
            let minutesDiff = (currentDateTime.getHours() - currentDateTime.getTimezoneOffset()) % 60;
            currentDateTime.setHours(hoursDiff);
            currentDateTime.setMinutes(minutesDiff);

            $("#StartTime").val(currentDateTime.toJSON().slice(0, 16));
            $("#StartTime").prop("min", currentDateTime.toJSON().slice(0, 16));
        });
    </script>
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Contest/Delete.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests.ContestViewModel

@{
    ViewData["Title"] = "Xoá kỳ kiểm tra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Xoá kỳ kiểm tra</h1>

<h3>Bạn có muốn xoá kỳ kiểm tra?</h3>
<div>
    <h4>Thông tin kỳ kiểm tra sẽ xoá</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubjectID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubjectID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ScoreTypeID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ScoreTypeID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher1ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Teacher1ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher2ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Teacher2ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Xoá" class="btn btn-danger" /> |
        <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách kỳ kiểm tra</a>
    </form>
</div>

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Contest/Details.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests.ContestViewModel

@{
    ViewData["Title"] = "Chi tiết kỳ kiểm tra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Chi tiết kỳ kiểm tra</h1>

<div>
    <h4>Chi tiết thông tin kỳ kiểm tra</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubjectID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubjectID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ScoreTypeID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ScoreTypeID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher1ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Teacher1ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Teacher2ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Teacher2ID)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.ID }, new { @class = "btn btn-primary" }) |
    <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách kỳ kiểm tra</a>
</div>

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Contest/Edit.cshtml
@model HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests.ContestCURequest

@{
    ViewData["Title"] = "Sửa thông tin kỳ kiểm tra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Sửa thông tin kỳ kiểm tra</h1>

<h4>Mẫu biểu sửa thông tin kỳ kiểm tra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Môn học</label>
                <select asp-for="SubjectID" class="form-control" asp-items="@(new SelectList(Model.Subjects, "ID", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Loại điểm</label>
                <select asp-for="ScoreTypeID" class="form-control" asp-items="@(new SelectList(Model.ScoreTypes, "ID", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartTime" class="control-label"></label>
                <input asp-for="StartTime" class="form-control" />
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" min="15" value="15" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Giáo viên 1</label>
                <select asp-for="Teacher1ID" class="form-control" asp-items="@(new SelectList(Model.Teachers, "Id", "Name"))">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Giáo viên 2</label>
                <select asp-for="Teacher2ID" class="form-control" asp-items="@(new SelectList(Model.Teachers, "Id", "Name"))">
                    <option value="@Guid.Empty">Không có giáo viên 2</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" /> |
                <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách kỳ kiểm tra</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $('#SubjectID').on('change', function () {
            var url = '@Url.Action("GetAllBySubjectID", "ScoreType")?subjectID=' + $(this).val();
            $.get(url, function (data) {
                var parentDiv = $("#ScoreTypeID").parent();
                $("#ScoreTypeID").remove();
                parentDiv.append(data);
            });
        });
    </script>
}

HeThongQuanLyCongTacKhaoThi.AdminApp/Views/Contest/Index.cshtml
@using HeThongQuanLyCongTacKhaoThi.ViewModels.Common;
@using HeThongQuanLyCongTacKhaoThi.ViewModels.Catalog.Contests;
@model PagedResult<ContestViewModel>

@{
    ViewData["Title"] = "Danh sách kỳ kiểm tra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Danh sách kỳ kiểm tra</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Tạo kỳ kiểm tra</a>
</p>

@if (ViewBag.SuccessMsg != null)
{
    <div id="alert-msg" class="alert alert-success" role="alert">
        @ViewBag.SuccessMsg
    </div>
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách kỳ kiểm tra</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <form id="dataTable_filter" class="form-inline" asp-action="Index" method="get">
                        <div class="form-group mr-sm-3 mb-2">
                            <label for="keyword" class="sr-only">Tìm kiếm:</label>
                            <input type="search" id="keyword" name="keyword" class="form-control form-control-sm" placeholder="Nội dung" aria-controls="dataTable">
                        </div>
                        <input class="btn btn-primary mb-2 mr-2" type="submit" value="Tìm kiếm" />
                        <input type="submit" class="btn btn-outline-primary mb-2" value="Tải lại" />
                    </form>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="table" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        Mã kỳ kiểm tra
                                    </th>
                                    <th>
                                        Tên kỳ kiểm tra
                                    </th>
                                    <th>
                                        Môn học
                                    </th>
                                    <th>
                                        Loại điểm
                                    </th>
                                    <th>
                                        Thời gian bắt đầu
                                    </th>
                                    <th>
                                        Khoảng thời gian
                                    </th>
                                    <th>
                                        Giáo viên chấm thi
                                    </th>
                                    <th>
                                        Hành động
                                    </th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>
                                        Mã kỳ kiểm tra
                                    </th>
                                    <th>
                                        Tên kỳ kiểm tra
                                    </th>
                                    <th>
                                        Môn học
                                    </th>
                                    <th>
                                        Loại điểm
                                    </th>
                                    <th>
                                        Thời gian bắt đầu
                                    </th>
                                    <th>
                                        Khoảng thời gian
                                    </th>
                                    <th>
                                        Giáo viên chấm thi
                                    </th>
                                    <th>
                                        Hành động
                                    </th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach (var item in Model.Items)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SubjectID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ScoreTypeName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.StartTime)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Duration)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TeacherNames)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) |
                                        @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                                        @Html.ActionLink("Xoá", "Delete", new { id = item.ID })
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div>
                    @await Component.InvokeAsync("Pager", Model)
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{


    <!-- Page level plugins -->
    <script src="/assets/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/assets/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script>
        setTimeout(function () {
            $("#alert-msg").fadeOut('slow');
        }, 1500);

        $(document).ready(function () {
            $('#table').DataTable({
                "paging": false,
                "ordering": true,
                "info": false,
                "bFilter": false
            });
        });
    </script>
}